WV.FeatureSwitch.Dashboard.Web/ViewModels/FeatureSwitchViewModel.cs
using System.Collections.Generic;
using WV.FeatureSwitch.Dashboard.Web.Models;

namespace WV.FeatureSwitch.Dashboard.Web.ViewModels
{
    public class FeatureSwitchViewModel
    {      
        public List<FeatureModel> Features { get; set; }

        public string CountrySite { get; set; }
        public int Status { get; set; }
    }
}

WV.FeatureSwitch.Dashboard.Web/Controllers/FeatureSwitchController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging;
using WV.FeatureSwitch.Dashboard.Web.APIClient;
using WV.FeatureSwitch.Dashboard.Web.ApiClientFactory.FactoryInterfaces;
using WV.FeatureSwitch.Dashboard.Web.Helper;
using WV.FeatureSwitch.Dashboard.Web.Models;
using WV.FeatureSwitch.Dashboard.Web.ViewModels;

namespace WV.FeatureSwitch.Dashboard.Web.Controllers
{
    [Authorize("Admin")] 
    public class FeatureSwitchController : Controller
    {
        private readonly IFeatureSwitchFactory _featureSwitchFactory;
        private readonly ILogger<FeatureSwitchController> _logger;
        private ApiResponse response;
        private readonly string pageName = "Feature Switch";
        private string _baseUrl = "";
        private string _listOfCountries = "";
        private List<FeatureSwitchViewModel> _featureSwitchViewModelList;

        public FeatureSwitchController(IFeatureSwitchFactory featureSwitchFactory, ILogger<FeatureSwitchController> logger, IConfiguration configuration)
        {
            _featureSwitchFactory = featureSwitchFactory;
            _logger = logger;
            response = new ApiResponse();
            _baseUrl = (AppConfigValues.ApiBaseUrl == null) ? configuration.GetSection("ApiConfig").GetSection("ApiBaseUrl").Value : AppConfigValues.ApiBaseUrl;
            _listOfCountries = (AppConfigValues.ApiCountry == null) ? configuration.GetSection("ApiConfig").GetSection("ApiCountry").Value : AppConfigValues.ApiCountry;
        }

        [ActivatorUtilitiesConstructor]
        public FeatureSwitchController(IFeatureSwitchFactory featureSwitchFactory, ILogger<FeatureSwitchController> logger, IConfiguration configuration, IEnumerable<FeatureSwitchViewModel> testFeatureModelList)
        {
            _featureSwitchFactory = featureSwitchFactory;
            _logger = logger;
            response = new ApiResponse();
            _baseUrl = (AppConfigValues.ApiBaseUrl == null) ? configuration.GetSection("ApiConfig").GetSection("ApiBaseUrl").Value : AppConfigValues.ApiBaseUrl;
            _listOfCountries = (AppConfigValues.ApiCountry == null) ? configuration.GetSection("ApiConfig").GetSection("ApiCountry").Value : AppConfigValues.ApiCountry;
            _featureSwitchViewModelList = testFeatureModelList.ToList();
        }

        // GET: FeatureSwitch       
        public async Task<ActionResult> Index(string notification)
        {
            try
            {
                // Call all the Feature Switch Models, to be displayed/returned to the View
                List<FeatureSwitchViewModel> featureViewModel = await GetAllFeatureLists();
 
                ViewBag.Notification = !string.IsNullOrEmpty(notification) ? notification : "";
                _logger.LogInformation(ConstantMessages.Load.Replace("{pageName}", pageName));

                return View(featureViewModel);
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, ConstantMessages.Error);
                response.Message = ConstantMessages.Error;
                return RedirectToAction("Error", "Home", response);
            }
        }

        /// <summary>
        /// Get All Feature Lists
        /// </summary>
        /// <returns></returns>
        public async Task<List<FeatureSwitchViewModel>> GetAllFeatureLists()
        {
            try
            {
                if (_featureSwitchViewModelList.Count == 0)
                {
                    FeatureSwitchViewModel featureSwitchViewModel;

                    // Check if we have a valid (not empty) URL (being passed in throught appsettings.json)
                    if (!string.IsNullOrEmpty(_baseUrl))
                    {
                        // Split the Comma-Seperated string of feature names and add them to a list
                        List<string> CountrySites = _listOfCountries.Split(',').ToList();

                        // Loop through all Feature Switch View Models for all country sites
                        foreach (string country in CountrySites)
                        {
                            // For each Feature Switch Model, create the appropriate url for it's country site
                            string url = UrlBuilder.BaseUrlBuilder(_baseUrl, country);
                            response = await _featureSwitchFactory.LoadList(url);
                            List<FeatureModel> featureSwitchViewModelList = response.ResponseObject as List<FeatureModel>;
                            var status = response.StatusCode;

                            featureSwitchViewModel = new FeatureSwitchViewModel();

                            // Add each Feature Switch View Model to a list of Feature Switch View Model
                            if (featureSwitchViewModelList != null)
                            {
                                featureSwitchViewModel.Features = featureSwitchViewModelList;
                                // Retrieve the full name of the Country Site (not the acronym)
                                featureSwitchViewModel.CountrySite = CountrySiteNameConstants.CountryName[country];
                                featureSwitchViewModel.Status = status;
                                _featureSwitchViewModelList.Add(featureSwitchViewModel);
                            }
                        }
                    }
                }               
                return _featureSwitchViewModelList;
            }
            catch(Exception ex)
            {
                _logger.LogError(ex, ConstantMessages.Error);
                return new List<FeatureSwitchViewModel>(); ;
            }           
        }

        /// <summary>
        /// Update Feature Flag
        /// </summary>
        /// <param name="flag">New Flag Status</param>
        /// <param name="inputFeatureNames">Names of all Features to be updated</param>
        /// <returns></returns>
        [Authorize("Admin")]
        public async Task<ActionResult> Update(bool flag, string inputFeatureNames)
        {
            ViewBag.Action = "Update";

            try
            {
                // Check if any features have been selected
                if (!string.IsNullOrEmpty(inputFeatureNames))
                {
                    // Split the Comma-Seperated string of feature names and add them to a list
                    List<string> inputFeatureNameList = inputFeatureNames.Split(',').ToList();

                    // This if statement is only for testing purposes
                    if (_featureSwitchViewModelList == null || _featureSwitchViewModelList.Count == 0)
                    {
                        _featureSwitchViewModelList = await GetAllFeatureLists();
                    }
                    
                    // Loop through all the Feature Switch View Models
                    foreach (var featureSwitchViewModel in _featureSwitchViewModelList)
                    {
                        // Retrieve the acronym for the Country Site. E.g. "Spain" will be "es"
                        string countryName = CountrySiteNameConstants.CountryName.FirstOrDefault(x => x.Value == featureSwitchViewModel.CountrySite).Key;
                        // For each Feature Switch Model, create the appropriate url for it's country site
                        string url = UrlBuilder.BaseUrlBuilder(_baseUrl, countryName);
                        List<FeatureModel> featureModels = featureSwitchViewModel.Features;
                       
                        // Check if there if any common feature names between the lists of the feature switch model, feature names and the selected feature names
                        var result = featureModels.Select(x => x.Name).Intersect(inputFeatureNameList);

                        // Do not enter if there is not common feature names between the lists of the feature switch model, feature names and the selected feature names
                        if (result.Any())
                        {
                            // Loop through the common feature names and update the feature flag status with the flag status specified in the parameter
                            foreach (var item in result)
                            {
                                var newFeatureModel = new FeatureModel() { Name = item, Flag = flag };
                                response = await _featureSwitchFactory.Create(newFeatureModel, url);
                            }
                        }
                    }                    
                    _logger.LogInformation(ConstantMessages.Load.Replace("{event}", pageName));
                }
                
                return RedirectToAction("Index", response);
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, ConstantMessages.Error);
                response.Message = ConstantMessages.Error;
                return RedirectToAction("Index", response);
            }
        }

        /// <summary>
        /// Bulk Create
        /// </summary>
        /// <param name="featureViewModel">New Feature to be created</param>
        /// <returns></returns>
        [HttpPost, ActionName("BulkCreate")]
        public async Task<ActionResult> BulkCreate(FeatureModel featureViewModel)
        {
            ViewBag.Action = "BulkCreate";
            try
            {
                if (ModelState.IsValid)
                {               
                    // Check if we have a valid (not empty) URL (being passed in throught appsettings.json)
                    if (!string.IsNullOrEmpty(_baseUrl))
                    {

WV.FeatureSwitch.Dashboard.Web/Views/FeatureSwitch/Index.cshtml
@model IEnumerable<WV.FeatureSwitch.Dashboard.Web.ViewModels.FeatureSwitchViewModel>

@{ }
<h4>Feature Switch Dashboard</h4>
@if (ViewBag.Notification != null)
{
    <span id="Notification" class="text-success pull-right">
        @ViewBag.Notification
    </span>}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

<div class="table-responsive">
    <table class="table">
        <thead>
            <tr>
                <th scope="col"></th>
                <th scope="col"></th>
                <th scope="col">
                    @using (Html.BeginForm("BulkCreate", "FeatureSwitch"))
                    {
                        <button>Create Feature Switch</button>
                    }
                </th>
                <th scope="col">
                    @using (Html.BeginForm("BulkDelete", "FeatureSwitch"))
                    {
                        <input hidden="hidden" type="text" id="CountrySiteName" name="CountrySiteName" value="Delete Feature Switch">
                        <br>
                        <input type="submit" value="Delete Feature Switch">
                    }
                </th>
            </tr>
            <tr>
                <th scope="col"></th>
                <th scope="col"></th>
                <th scope="col"></th>
                <th scope="col">
                    @using (Html.BeginForm("Update", "FeatureSwitch"))
                    {
                        <label for="flag">Update selected features to: </label>
                        <input hidden="hidden" id="inputFeatureNames" name="inputFeatureNames" />
                        <select id="flag" name="flag">
                            <option value="True">True</option>
                            <option value="False">False</option>
                        </select>
                        <input type="submit" id="UpdateBtn" name="UpdateBtn" value="Update" disabled="disabled" onclick="Update">
                    }
                </th>
            </tr>
        </thead>
        <tbody>

            @foreach (var item in Model)
            {
                <tr class="accordion-toggle collapsed" id="accordion1" data-toggle="collapse" data-parent="#accordion1" href="#collapseOne">
                    <td class="expand-button">@item.CountrySite</td>
                    <td>
                        @if (@item.Status == 200)
                        {
                            <p class="fa fa-check" style="color:green;"></p>
                        }
                        else
                        {
                            <p class="fa fa-times" style="color:red;"></p>
                        }
                    </td>
                    <td></td>
                    <td>
                        @using (Html.BeginForm("ResetAll", "FeatureSwitch"))
                        {
                            <input hidden="hidden" type="text" name="CountrySiteName" value="@item.CountrySite">
                            <br>
                            <input type="submit" value="Reset">
                        }
                    </td>

                </tr>
                <tr class="hide-table-padding">
                    <td></td>
                    <td colspan="3">
                        <div id="collapseOne" class="collapse in p-3">
                            <div class="row">
                                <div class="col-4">Select</div>
                                <div class="col-4">Name</div>
                                <div class="col-4">Flag</div>
                            </div>

                            @foreach (var record in item.Features)
                            {
                                <div id="SelectedFeature" class="row">
                                    <div id="myDiv" class="col-4">
                                        <input class="source" type="checkbox" name="type" value="@record.Name">                                        
                                    </div>
                                    <div class="col-4">@record.Name</div>
                                    <div class="col-4">
                                        @if (@record.Flag == true)
                                        {
                                            <p>On</p>
                                        }
                                        else
                                        {
                                            <p>Off</p>
                                        }
                                    </div>
                                </div>
                            }
                        </div>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

@section scripts{

        <script>
            $('#myDiv input[type=checkbox]').change(function () {

                var featureArray = new Array();
                $("#myDiv input[type='checkbox']:checked").each(function () {
                    featureArray[featureArray.length] = this.value;
                });
                console.log(featureArray);
                $('#inputFeatureNames').val(featureArray);

                $(document).ready(function () {
                    if (!featureArray.length) {
                        document.getElementById("UpdateBtn").disabled = true;
                    } else {
                        document.getElementById("UpdateBtn").disabled = false;
                    }
                });
            });
        </script>  
}